version: "3.8"

services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: sh -c "echo $POSTGRES_USER $POSTGRES_PASSWORD $POSTGRES_DB $POSTGRES_HOST $POSTGRES_PORT && gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 user_registration:app"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
